/**
 * Generated by Supabase MCP (`generate_typescript_types`) after
 * applying migrations 0001_auth and 0002_tracking.
 *
 * To refresh after new migrations: call the MCP again or
 * `npx supabase gen types typescript --project-id oqslwfxugwvaqsfbemzi > app/types/database.types.ts`.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: number
          meta: Json
          target_id: string | null
          target_type: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: never
          meta?: Json
          target_id?: string | null
          target_type: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: never
          meta?: Json
          target_id?: string | null
          target_type?: string
        }
        Relationships: []
      }
      invites: {
        Row: {
          created_at: string
          created_by: string | null
          email: string
          expires_at: string
          role: Database['public']['Enums']['user_role']
          token: string
          used_at: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          email: string
          expires_at?: string
          role?: Database['public']['Enums']['user_role']
          token?: string
          used_at?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          email?: string
          expires_at?: string
          role?: Database['public']['Enums']['user_role']
          token?: string
          used_at?: string | null
        }
        Relationships: []
      }
      lead_events: {
        Row: {
          created_at: string
          id: number
          lead_id: string | null
          meta: Json
          path: string | null
          target: string | null
          type: string
          visitor_id: string | null
        }
        Insert: {
          created_at?: string
          id?: never
          lead_id?: string | null
          meta?: Json
          path?: string | null
          target?: string | null
          type: string
          visitor_id?: string | null
        }
        Update: {
          created_at?: string
          id?: never
          lead_id?: string | null
          meta?: Json
          path?: string | null
          target?: string | null
          type?: string
          visitor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'lead_events_lead_id_fkey'
            columns: ['lead_id']
            isOneToOne: false
            referencedRelation: 'leads'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'lead_events_visitor_id_fkey'
            columns: ['visitor_id']
            isOneToOne: false
            referencedRelation: 'visitors'
            referencedColumns: ['id']
          }
        ]
      }
      lead_notes: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          lead_id: string
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          lead_id: string
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          lead_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'lead_notes_lead_id_fkey'
            columns: ['lead_id']
            isOneToOne: false
            referencedRelation: 'leads'
            referencedColumns: ['id']
          }
        ]
      }
      leads: {
        Row: {
          contact_value: string | null
          created_at: string
          display_name: string | null
          first_seen: string
          id: string
          last_seen: string
          notes: string | null
          source: string | null
          status: Database['public']['Enums']['lead_status']
          utm_campaign: string | null
          utm_medium: string | null
          utm_source: string | null
          visitor_id: string | null
        }
        Insert: {
          contact_value?: string | null
          created_at?: string
          display_name?: string | null
          first_seen?: string
          id?: string
          last_seen?: string
          notes?: string | null
          source?: string | null
          status?: Database['public']['Enums']['lead_status']
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          visitor_id?: string | null
        }
        Update: {
          contact_value?: string | null
          created_at?: string
          display_name?: string | null
          first_seen?: string
          id?: string
          last_seen?: string
          notes?: string | null
          source?: string | null
          status?: Database['public']['Enums']['lead_status']
          utm_campaign?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          visitor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'leads_visitor_id_fkey'
            columns: ['visitor_id']
            isOneToOne: false
            referencedRelation: 'visitors'
            referencedColumns: ['id']
          }
        ]
      }
      link_clicks: {
        Row: {
          created_at: string
          href: string
          id: number
          label: string | null
          visitor_id: string | null
        }
        Insert: {
          created_at?: string
          href: string
          id?: never
          label?: string | null
          visitor_id?: string | null
        }
        Update: {
          created_at?: string
          href?: string
          id?: never
          label?: string | null
          visitor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'link_clicks_visitor_id_fkey'
            columns: ['visitor_id']
            isOneToOne: false
            referencedRelation: 'visitors'
            referencedColumns: ['id']
          }
        ]
      }
      notes: {
        Row: {
          body: string
          created_at: string
          id: string
          pinned: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          pinned?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          pinned?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          disabled: boolean
          full_name: string | null
          id: string
          role: Database['public']['Enums']['user_role']
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          disabled?: boolean
          full_name?: string | null
          id: string
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          disabled?: boolean
          full_name?: string | null
          id?: string
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          archived: boolean
          color: string | null
          created_at: string
          description: string | null
          id: string
          name: string
          owner_id: string | null
          slug: string
          updated_at: string
        }
        Insert: {
          archived?: boolean
          color?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_id?: string | null
          slug: string
          updated_at?: string
        }
        Update: {
          archived?: boolean
          color?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_id?: string | null
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      project_members: {
        Row: {
          created_at: string
          project_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          project_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          project_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_members_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      sprints: {
        Row: {
          created_at: string
          ends_at: string
          goal: string | null
          id: string
          name: string
          project_id: string
          starts_at: string
        }
        Insert: {
          created_at?: string
          ends_at: string
          goal?: string | null
          id?: string
          name: string
          project_id: string
          starts_at: string
        }
        Update: {
          created_at?: string
          ends_at?: string
          goal?: string | null
          id?: string
          name?: string
          project_id?: string
          starts_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'sprints_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      stories: {
        Row: {
          body: string | null
          created_at: string
          id: string
          project_id: string
          title: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          project_id: string
          title: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          project_id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: 'stories_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      tasks: {
        Row: {
          assignee_id: string | null
          created_at: string
          description: string | null
          done_at: string | null
          id: string
          points: number | null
          position: number
          project_id: string
          sprint_id: string | null
          status: Database['public']['Enums']['task_status']
          story_id: string | null
          title: string
          updated_at: string
        }
        Insert: {
          assignee_id?: string | null
          created_at?: string
          description?: string | null
          done_at?: string | null
          id?: string
          points?: number | null
          position?: number
          project_id: string
          sprint_id?: string | null
          status?: Database['public']['Enums']['task_status']
          story_id?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          assignee_id?: string | null
          created_at?: string
          description?: string | null
          done_at?: string | null
          id?: string
          points?: number | null
          position?: number
          project_id?: string
          sprint_id?: string | null
          status?: Database['public']['Enums']['task_status']
          story_id?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tasks_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'tasks_sprint_id_fkey'
            columns: ['sprint_id']
            isOneToOne: false
            referencedRelation: 'sprints'
            referencedColumns: ['id']
          }
        ]
      }
      task_labels: {
        Row: {
          color: string | null
          id: string
          name: string
          project_id: string
        }
        Insert: {
          color?: string | null
          id?: string
          name: string
          project_id: string
        }
        Update: {
          color?: string | null
          id?: string
          name?: string
          project_id?: string
        }
        Relationships: []
      }
      task_label_links: {
        Row: {
          label_id: string
          task_id: string
        }
        Insert: {
          label_id: string
          task_id: string
        }
        Update: {
          label_id?: string
          task_id?: string
        }
        Relationships: []
      }
      visitors: {
        Row: {
          anon_id: string
          country: string | null
          first_seen: string
          id: string
          language: string | null
          last_seen: string
          referrer: string | null
          user_agent: string | null
          utm_campaign: string | null
          utm_content: string | null
          utm_medium: string | null
          utm_source: string | null
          utm_term: string | null
        }
        Insert: {
          anon_id: string
          country?: string | null
          first_seen?: string
          id?: string
          language?: string | null
          last_seen?: string
          referrer?: string | null
          user_agent?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Update: {
          anon_id?: string
          country?: string | null
          first_seen?: string
          id?: string
          language?: string | null
          last_seen?: string
          referrer?: string | null
          user_agent?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      is_editor_or_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      lead_status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
      task_status: 'todo' | 'doing' | 'review' | 'done'
      user_role: 'admin' | 'editor' | 'viewer'
    }
    CompositeTypes: Record<string, never>
  }
}
